name: salati
description: تطبيق شجرة النسب - سلالتي
publish_to: 'none'
version: 3.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#3E2723"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
  min_sdk_android: 21
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
